apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: syncplant-backend
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    exporters:
      debug:
      otlp:
        endpoint: http://signoz-otel-collector.signoz:4317
        tls:
          insecure: true
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        endpoint: http://vmagent-vm-victoria-metrics-k8s-stack.prometheus.svc.cluster.local:8429/opentelemetry
        tls:
            insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp,otlphttp/victoriametrics]

