apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nacos.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- toYaml .Values.annotations | indent 4 }}
spec:
  {{- if eq .Values.global.mode "cluster" }}
  serviceName: nacos-hs
  {{- else }}
  serviceName: nacos-cs
  {{- end }}
  replicas: {{ .Values.nacos.replicaCount }}
  {{- if .Values.nacos.podManagementPolicy }}
  podManagementPolicy: {{ .Values.nacos.podManagementPolicy }}
  {{- else}}
  podManagementPolicy: OrderedReady
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nacos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nacos.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.nacos.image.repository }}:{{ .Values.nacos.image.tag }}"
          imagePullPolicy: {{ .Values.nacos.image.pullPolicy }}
          # startupProbe:
          #   initialDelaySeconds: 120
          #   periodSeconds: 5
          #   timeoutSeconds: 10
          #   httpGet:
          #     scheme: HTTP
          #     port: {{ .Values.nacos.serverPort }}
          #     path: /nacos/v1/console/health/readiness
          # livenessProbe:
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 10
          #   httpGet:
          #     scheme: HTTP
          #     port: {{ .Values.nacos.serverPort }}
          #     path: /nacos/v1/console/health/liveness
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NACOS_SERVER_PORT
              value: {{ .Values.nacos.serverPort | quote }}
            - name: NACOS_APPLICATION_PORT
              value: {{ .Values.nacos.serverPort | quote }}
            - name: NACOS_AUTH_ENABLE
              value: {{ .Values.auth.enabled | quote }}
            - name: NACOS_AUTH_TOKEN_EXPIRE_SECONDS
              value: {{ .Values.auth.seconds | quote }}
            - name: NACOS_AUTH_SYSTEM_TYPE
              value: {{ .Values.auth.type | quote }}
            - name: NACOS_AUTH_TOKEN
              value: {{ .Values.auth.token | quote }}
            - name: NACOS_AUTH_IDENTITY_KEY
              value: {{ .Values.auth.key | quote }}
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: {{ .Values.auth.value | quote }}
            - name: PREFER_HOST_MODE
              value: {{ .Values.nacos.preferhostmode | quote }}
            - name: NACOS_REPLICAS
              value: "3"
              value: "hostname"
            - name: JAVA_OPT
              value: "-Xms1g -Xmx3g"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-cs.middle.svc.cluster.local:8848 nacos-1.nacos-cs.middle.svc.cluster.local:8848 nacos-2.nacos-cs.middle.svc.cluster.local:8848"
            {{- if eq .Values.nacos.storage.type "mysql" }}
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: MYSQL_SERVICE_DB_PARAM
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.param
            {{else}}
            - name: EMBEDDED_STORAGE
              value: embedded
          {{end}}
          volumeMounts:
            - name: data
              mountPath: /home/nacos/data
              subPath: data
            - name: data
              mountPath: /home/nacos/logs
              subPath: logs
      {{- if not .Values.persistence.enabled  }}
      volumes:
        - name: data
          emptyDir: { }
  {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
  {{- toYaml .Values.persistence.data | nindent 8 }}
  {{- end }}

